#!/bin/sh -e

CA=configure.ac
AM=GNUmakefile.am

(rm -f $CA && sed '/^m4_define..SVNINFO/ s/svn info/cat svninfo/' > $CA) < $CA

grep platform_win32.cpp $AM > /dev/null 2>&1 || \
(rm -f $AM && sed '/libplatform.io.FileSystem_win32.cpp/ a \
	libplatform/platform_win32.cpp    \\
' >$AM) < $AM

echo "Running autoreconf..."
autoreconf -ivf "$@"

echo "Now run ./configure and then make to build MP4v2"
